CREATE TABLE DBVERSION (
	VALUE INTEGER NOT NULL,
	UPDATED TIMESTAMP NOT NULL
);

CREATE TABLE CONFIGURATION (
	NAME VARCHAR(40) NOT NULL,
	VALUE VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CONFIGURATION PRIMARY KEY (NAME)
);

CREATE TABLE USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	MODE VARCHAR(10) NOT NULL,
	IDENTIFIER VARCHAR(200) NOT NULL,
	PASSWORD VARCHAR(300) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	FIRSTNAME VARCHAR(40) NOT NULL,
	LASTNAME VARCHAR(40) NOT NULL,
	CONSTRAINT PK_USERS PRIMARY KEY (ID),
	CONSTRAINT UQ_USER_IDENTIFIER UNIQUE (IDENTIFIER),
	CONSTRAINT UQ_USER_EMAIL UNIQUE (EMAIL)
);
