CREATE TABLE DBVERSION (
	VALUE INTEGER NOT NULL,
	UPDATED TIMESTAMP NOT NULL
);

CREATE TABLE CONFIGURATION (
	NAME VARCHAR(40) NOT NULL,
	VALUE VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CONFIGURATION PRIMARY KEY (NAME)
);

CREATE TABLE USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	MODE VARCHAR(10) NOT NULL,
	IDENTIFIER VARCHAR(200) NOT NULL,
	PASSWORD VARCHAR(300) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	FIRSTNAME VARCHAR(40) NOT NULL,
	LASTNAME VARCHAR(40) NOT NULL,
	CONSTRAINT PK_USERS PRIMARY KEY (ID),
	CONSTRAINT UQ_USER_IDENTIFIER UNIQUE (IDENTIFIER),
	CONSTRAINT UQ_USER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE SCHOOLS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	TEACHER INTEGER NOT NULL,
	NAME VARCHAR(80) NOT NULL,
	COLOR CHAR(6) NOT NULL,
	CONSTRAINT PK_SCHOOLS PRIMARY KEY (ID),
	CONSTRAINT UQ_SCHOOLS UNIQUE (TEACHER, NAME),
	CONSTRAINT FK_SCHOOL_USER FOREIGN KEY (TEACHER) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE TABLE COORDINATES (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ENTITY_TYPE VARCHAR(20) NOT NULL,
	ENTITY_ID INTEGER NOT NULL,
	COORD_TYPE VARCHAR(20) NOT NULL,
	COORD_VALUE VARCHAR(150) NOT NULL,
	CONSTRAINT PK_COORDINATES PRIMARY KEY (ID),
	CONSTRAINT UQ_COORDINATES UNIQUE (ENTITY_TYPE, ENTITY_ID, COORD_TYPE)
);