CREATE TABLE DBVERSION (
	VALUE INTEGER NOT NULL,
	UPDATED TIMESTAMP NOT NULL
);

CREATE TABLE CONFIGURATION (
	NAME VARCHAR(40) NOT NULL,
	VALUE VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CONFIGURATION PRIMARY KEY (NAME)
);

CREATE TABLE TEACHERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	OPENID VARCHAR(120) NOT NULL,
	FIRSTNAME VARCHAR(40) NOT NULL,
	LASTNAME VARCHAR(40) NOT NULL,
	CONSTRAINT PK_TEACHERS PRIMARY KEY (ID),
	CONSTRAINT UQ_TEACHERS UNIQUE (OPENID)
);

CREATE TABLE SCHOOLS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	TEACHER INTEGER NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT PK_SCHOOLS PRIMARY KEY (ID),
	CONSTRAINT FK_SCHOOL_TEACHER FOREIGN KEY (TEACHER) REFERENCES TEACHERS (ID) ON DELETE CASCADE
);

CREATE TABLE STUDENTS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	SCHOOL INTEGER NOT NULL,
	FIRSTNAME VARCHAR(40) NOT NULL,
	LASTNAME VARCHAR(40) NOT NULL,
	CONSTRAINT PK_STUDENTS PRIMARY KEY (ID),
	CONSTRAINT FK_STUDENT_SCHOOL FOREIGN KEY (SCHOOL) REFERENCES SCHOOLS (ID) ON DELETE CASCADE
);

CREATE TABLE LESSONS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	STUDENT INTEGER NOT NULL,
	START DATETIME NOT NULL,
	END DATETIME NOT NULL,
	CONSTRAINT PK_LESSONS PRIMARY KEY (ID),
	CONSTRAINT FK_LESSON_STUDENT FOREIGN KEY (STUDENT) REFERENCES STUDENTS (ID) ON DELETE CASCADE
);

CREATE TABLE COORDINATES (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	OWNER_TYPE VARCHAR(10) NOT NULL,
	OWNER_ID INTEGER NOT NULL,
	CONTACT_TYPE VARCHAR(20) NOT NULL,
	CONTACT_INFO VARCHAR(200) NOT NULL,
	CONTACT_NAME VARCHAR(80) NULL,
	CONSTRAINT PK_COORDINATES PRIMARY KEY (ID)
);

CREATE TABLE COMMENTS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	OWNER_TYPE VARCHAR(10) NOT NULL,
	OWNER_ID INTEGER NOT NULL,
	TITLE VARCHAR(100) NULL,
	CONTENT VARCHAR(3000) NULL,
	CREATION DATETIME NOT NULL,
	CONSTRAINT PK_COMMENTS PRIMARY KEY (ID)
);