-- User preferences
CREATE TABLE PREFERENCES (
	USERID INTEGER NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	VALUE VARCHAR(300) NULL,
	CONSTRAINT PK_PREFERENCES PRIMARY KEY (USERID, NAME),
	CONSTRAINT FK_PREFERENCES_USER FOREIGN KEY (USERID) REFERENCES USERS (ID)
);
