CREATE TABLE STUDENTS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	SCHOOL INTEGER NOT NULL,
	SUBJECT VARCHAR(80) NOT NULL,
	FIRSTNAME VARCHAR(40) NOT NULL,
	LASTNAME VARCHAR(40) NOT NULL,
	CONSTRAINT PK_STUDENTS PRIMARY KEY (ID),
	CONSTRAINT FK_STUDENT_SCHOOL FOREIGN KEY (SCHOOL) REFERENCES SCHOOLS (ID) ON DELETE CASCADE
);