-- Students can be disabled

ALTER TABLE STUDENTS ADD COLUMN DISABLED BOOLEAN;
UPDATE STUDENTS SET DISABLED = FALSE;
ALTER TABLE STUDENTS ALTER COLUMN DISABLED SET NOT NULL;

-- @rollback
ALTER TABLE STUDENTS DROP COLUMN IF EXISTS DISABLED;

-- @mysql

ALTER TABLE STUDENTS ADD COLUMN DISABLED BOOLEAN;
UPDATE STUDENTS SET DISABLED = FALSE;
ALTER TABLE STUDENTS MODIFY COLUMN DISABLED BOOLEAN NOT NULL;

-- @mysql-rollback
ALTER TABLE STUDENTS DROP COLUMN DISABLED;
