-- Using only a 'name' for the students

ALTER TABLE STUDENTS ALTER COLUMN LASTNAME RENAME TO NAME;
ALTER TABLE STUDENTS ALTER COLUMN NAME VARCHAR(80);

UPDATE STUDENTS SET NAME = CONCAT (FIRSTNAME, ' ', NAME);

ALTER TABLE STUDENTS DROP COLUMN FIRSTNAME;

--  @mysql

ALTER TABLE STUDENTS CHANGE COLUMN LASTNAME NAME VARCHAR(80);

UPDATE STUDENTS SET NAME = CONCAT (FIRSTNAME, ' ', NAME);

ALTER TABLE STUDENTS DROP COLUMN FIRSTNAME;
