CREATE TABLE COMMENTS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ENTITY_TYPE VARCHAR(20) NOT NULL,
	ENTITY_ID INTEGER NOT NULL,
	TEACHER INTEGER NOT NULL,
	CREATION TIMESTAMP NOT NULL,
	EDITION TIMESTAMP NOT NULL,
	CONTENT VARCHAR(3000) NULL,
	CONSTRAINT PK_COMMENTS PRIMARY KEY (ID),
	CONSTRAINT FK_COMMENTS_TEACHER FOREIGN KEY (TEACHER) REFERENCES USERS (ID) ON DELETE CASCADE
);