CREATE TABLE LESSONS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	STUDENT INTEGER NOT NULL,
	PDATE CHAR(10) NOT NULL,
	PFROM CHAR(5) NOT NULL,
	PTO CHAR(5) NOT NULL,
	LOCATION VARCHAR(80) NULL,
	CONSTRAINT PK_LESSONS PRIMARY KEY (ID),
	CONSTRAINT FK_LESSON_STUDENT FOREIGN KEY (STUDENT) REFERENCES STUDENTS (ID) ON DELETE CASCADE
);