CREATE TABLE COMMENTS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	ENTITY_TYPE VARCHAR(20) NOT NULL,
	ENTITY_ID INTEGER NOT NULL,
	CREATION TIMESTAMP NOT NULL,
	EDITION TIMESTAMP NULL,
	CONTENT VARCHAR(3000) NULL,
	CONSTRAINT PK_COMMENTS PRIMARY KEY (ID)
);