-- Adds the additional columns
ALTER TABLE COMMENTS ADD COLUMN SCHOOL INTEGER NULL;
ALTER TABLE COMMENTS ADD COLUMN STUDENT INTEGER NULL;
ALTER TABLE COMMENTS ADD COLUMN LESSON INTEGER NULL;

-- Adds the additional constraints
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENT_SCHOOL FOREIGN KEY (SCHOOL) REFERENCES SCHOOLS (ID) ON DELETE CASCADE;
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENT_STUDENT FOREIGN KEY (STUDENT) REFERENCES STUDENTS (ID) ON DELETE CASCADE;
ALTER TABLE COMMENTS ADD CONSTRAINT FK_COMMENT_LESSON FOREIGN KEY (LESSON) REFERENCES LESSONS (ID) ON DELETE CASCADE;

-- Clean-up
DELETE FROM COMMENTS WHERE ENTITY_TYPE = 'SCHOOLS' AND ENTITY_ID NOT IN (SELECT ID FROM SCHOOLS);
DELETE FROM COMMENTS WHERE ENTITY_TYPE = 'STUDENTS' AND ENTITY_ID NOT IN (SELECT ID FROM STUDENTS);
DELETE FROM COMMENTS WHERE ENTITY_TYPE = 'LESSONS' AND ENTITY_ID NOT IN (SELECT ID FROM LESSONS);

-- Copy
UPDATE COMMENTS SET SCHOOL = ENTITY_ID WHERE ENTITY_TYPE = 'SCHOOLS';
UPDATE COMMENTS SET STUDENT = ENTITY_ID WHERE ENTITY_TYPE = 'STUDENTS';
UPDATE COMMENTS SET LESSON = ENTITY_ID WHERE ENTITY_TYPE = 'LESSONS';

-- Removes the entity columns
ALTER TABLE COMMENTS DROP COLUMN ENTITY_TYPE;
ALTER TABLE COMMENTS DROP COLUMN ENTITY_ID;
